<?php
/**
 * Do not edit this file. Edit config/app.php instead.
 * This file is required in the root directory so WordPress can find it. WP is
 * hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/app.php');
require_once(ABSPATH . 'wp-settings.php');
